import { eq } from 'drizzle-orm';
import { db } from '../config/db.js';
import { prospects, playbooks } from '../db/schema.js';
import type { ExtractedPatterns } from './pattern-extraction.service.js';

// ── Generate Playbooks ───────────────────────────
// TODO: Replace stub with Claude API calls in a later step
// Each prospect gets a personalized playbook generated by LLM

export async function generatePlaybooks(
  analysisId: string,
  extractedPatterns: ExtractedPatterns,
): Promise<number> {
  // Fetch prospects for this analysis
  const prospectList = await db
    .select()
    .from(prospects)
    .where(eq(prospects.analysisId, analysisId));

  if (prospectList.length === 0) return 0;

  const playbookValues = prospectList.map((prospect) => ({
    analysisId,
    prospectId: prospect.id,
    coldEmail: {
      subject: `How ${prospect.companyName} can reduce pipeline review time by 60%`,
      body: `Hi ${prospect.contactName},\n\nI noticed ${prospect.companyName} is in the ${prospect.industry} space — similar to several of our customers who were spending 10+ hours/week on manual data entry before switching.\n\nWe helped a comparable company cut their pipeline review time by 60% and improve forecast accuracy by 40%.\n\nWould you be open to a 15-minute call next week to explore if we could do the same for your team?\n\nBest,\n[Your Name]`,
      followUp: `Hi ${prospect.contactName}, just wanted to bump this to the top of your inbox. Happy to share a quick case study if helpful.`,
    },
    discoveryQuestions: [
      `How does your team currently track pipeline health at ${prospect.companyName}?`,
      'What does your forecasting process look like today?',
      'How much time does your team spend on manual CRM updates each week?',
      'What would it mean for your team if you could predict close dates within 5 days?',
      'Who else on your team would be involved in evaluating a solution like this?',
    ],
    painPoints: extractedPatterns.painPoints.map((pp) => ({
      painPoint: pp,
      relevance: `Based on similar companies in ${prospect.industry}`,
    })),
    objectionHandling: extractedPatterns.commonObjections.map((obj) => ({
      objection: obj,
      response: obj.includes('CRM')
        ? `We integrate with your existing CRM — we enhance it rather than replace it. Most of our ${prospect.industry} customers saw ROI within 30 days.`
        : obj.includes('budget')
          ? `Many of our customers started with a pilot program. The ROI from reduced manual work typically covers the cost within the first quarter.`
          : `We hear that often. What we've found is that champions like yourself can run a small pilot that shows clear value to the broader team within 2-3 weeks.`,
    })),
    championPersona: {
      role: prospect.contactTitle,
      motivations: [
        'Improve team efficiency',
        'Better pipeline visibility',
        'Accurate revenue forecasting',
      ],
      buyingTriggers: [
        'End of quarter pressure',
        'New leadership wanting visibility',
        'Missed forecast targets',
      ],
    },
    predictedTimeline: {
      daysToClose: extractedPatterns.avgSalesCycleDays,
      stages: [
        { stage: 'Discovery Call', day: 0 },
        { stage: 'Demo', day: 7 },
        { stage: 'Technical Review', day: 14 },
        { stage: 'Proposal', day: Math.round(extractedPatterns.avgSalesCycleDays * 0.6) },
        { stage: 'Negotiation', day: Math.round(extractedPatterns.avgSalesCycleDays * 0.8) },
        { stage: 'Closed Won', day: extractedPatterns.avgSalesCycleDays },
      ],
    },
    caseStudyRef: {
      company: 'Similar Company (Anonymized)',
      industry: prospect.industry,
      result: 'Reduced pipeline review time by 60%, improved forecast accuracy by 40%',
      quote: '"This tool completely transformed how our sales team operates." — VP of Sales',
    },
    rawLlmOutput: 'STUB — no LLM call made',
  }));

  await db.insert(playbooks).values(playbookValues);

  return playbookValues.length;
}
